apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homework
  name: hw2-dp
  labels:
    app: hw2-dp
spec:
  selector:
    matchLabels:
      app: hw2-dp
  strategy:                     # стратегия обновления
    rollingUpdate:
      maxSurge: 1                 # обновление подов за раз
      maxUnavailable: 1           # максимально недоступно подов
    type: RollingUpdate
  replicas: 3                   # реплики пода
  template:
    metadata:
      name: hw1-pod
      labels:
        app: hw2-dp
    spec:
      nodeSelector:
        homework: "true"
      initContainers:
      - name: init
        image: busybox:latest
        command: ['sh', '-c', 'echo "[Homework #1] Hello, World!" > /init/index.html']
        volumeMounts:
        - name: shared-dir
          mountPath: "/init"
      containers:
      - name: nginx
        image: nginx:latest
        command: ["/bin/sh"]
        args: ["-c", "sed -i 's/80/8000/' /etc/nginx/conf.d/default.conf && ln -sf /homework/* /usr/share/nginx/html && nginx -g 'daemon off;'"]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: shared-dir
          mountPath: /homework
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","rm -f /homework/index.html"]
        readinessProbe:
          exec:
            command:
            - cat
            - /homework/index.html
          initialDelaySeconds: 5        # задержка 5 секунд перед первой пробой
          periodSeconds: 5              # проба каждые 5 секунд
      volumes:
      - name: shared-dir
        emptyDir: {}
